language: cpp

compiler:
    - gcc

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libbobcat-dev
    - libgcrypt11-dev
    - libboost-dev
    - libgnutls-dev


before_script:
    - CXX=g++-4.8 cmake .

script:
    - make DESTDIR=/tmp/prefix install
    - ./ccbuild -j 1 -C src
