language: cpp

compiler:
  - gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.8 libbobcat-dev libgcrypt11-dev libboost-dev libgnutls-openssl-dev

before_script:
  - CXX=g++-4.8 cmake .

script: make
