#!/bin/sh

if [ "x$1" = "xclean" ]; then
	echo Cleaning
	make distclean
  rm -f configure Makefile.in depcomp missing Makefile.am aclocal.m4 install-sh
  rm -rf autom4te.cache
	exit
fi
## Generate Makefile.am from ccbuild
PSOURCE=src/ccbuild.cc
PNAME=`basename "${PSOURCE}" .cc`
echo "Generating Makefile.am from ccbuild"
which ccbuild && (ccbuild md5 --recursive-include . "${PSOURCE}" > MD5SUMS)
SOURCES=`sed  -r 's/^[a-z0-9]+  //; s/ /\\ /' < MD5SUMS | tr '\n' ' '`

#Overwrite Makefile.am
cat > Makefile.am <<EOF
AUTOMAKE_OPTIONS = subdir-objects

bin_PROGRAMS = ${PNAME}

#Sources, generated list from ccbuild md5 output
${PNAME}_SOURCES = ${SOURCES}	

${PNAME}_CXXFLAGS = \${DEPS_CFLAGS} -DNODEBUG -fopenmp
${PNAME}_LDADD = \${DEPS_LIBS} -lbobcat -lgomp

#Flex it!
src/SourceScanner/yylex.cc: src/SourceScanner/lexer
	\${LEX} \$<
	mv yylex.cc \$@

EOF

echo "Running autotools:"
##BOOTSTRAP
echo " aclocal"
aclocal #Sometimes nice to have: -I /usr/share/autoconf-archive
echo " autoconf"
autoconf
echo " automake"
automake --add-missing


