name: release

on: [push]

# on: 
#   push:
#     tags:
#     - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        sudo apt-get install -y libgnutls28-dev g++ libbobcat-dev libgcrypt11-dev libboost-dev flex libfl-dev
        cmake .
    - name: Build
      run: cmake --build . --config Release
    - name: Package
      run: ./package.sh
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "ccbuild*.tar.gz"
        bodyFile: "release.md"
        token: ASDF
        # token: ${{ secrets.GITHUB_TOKEN }}